spring:
  application:
    name: ApiGateway

  r2dbc:
    url: r2dbc:mssql://localhost:1433/teskos
    username: furi
    password: furi1234

  cloud:
    gateway:
      routes:
        - id: PurchaseService
          uri: http://localhost:8083
          predicates:
            - Path=/api/purchase/**

        - id: BalanceService
          uri: http://localhost:8084
          predicates:
            - Path=/api/profile/**
#
#        - id: email-service
#          uri: http://localhost:5002
#          predicates:
#            - Path=/api/v1/email/**

jwt:
  secret:
    key: furigatengfurigatengfurigatengfurigatengfurigatengfurigateng

server:
  port: 8888
